tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "bash"
brew "bash-completion@2"
brew "coreutils"
brew "findutils"
brew "fzf"
brew "git"
brew "gnu-sed", args: ["with-default-names"]
brew "grep"
brew "hugo"
brew "node"
brew "openssh"
brew "tree"
brew "vim", args: ["with-override-system-vi"]
brew "wget"
cask "docker"
cask "google-chrome"
cask "gpg-suite"
cask "iterm2"
